name: NPM Build
run-name: ${{ gitea.actor }} is building Home Assistant Number Icons
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Update text-to-svg from master
        run: |
          rm -rf node_modules/text-to-svg
          git clone --depth=1 https://github.com/congpeijun/text-to-svg.git -b congpeijun-patch-1 node_modules/text-to-svg
          npm install --prefix node_modules/text-to-svg
          npm run build --prefix node_modules/text-to-svg
      - name: Run lint
        run: npm run lint
      - name: Run dist
        run: npm run dist
