---
name: Lint
# yamllint disable-line rule:truthy
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run yamllint
        uses: frenck/action-yamllint@v1.5.0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Node linter
        run: npm run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from Gitea
        uses: actions/checkout@v4
      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{json,js,ts,mjs,md,yaml}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
