---
name: Release package

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from Gitea
        uses: actions/checkout@v4
      - name: Create release
        uses: akkuman/gitea-release-action@v1
        with:
          files: |-
            number-icons.js
      - name: Publish package
        uses: VAllens/gitea-publish-generic-packages@v1
        with:
          files: |-
            number-icons.js
          token: ${{ secrets.PACKAGES_TOKEN }}
